import {WaColumnKind} from "@/core/columns/WaColumnEnum";

export interface WaGridColumnDef {
    _rowId?: number,
    _rowMode?: string,
    _isChecked?: boolean,
    _number?: number,
    _mode?: any,
    _checkbox?: any,
    _parentNumber?: number,
    _depth?: number;
    _childRowIds?: any[],
    _childRows?: any[],
    _childCount?: number,
    _isOpen?: boolean,
    _isShow?: boolean,
    open?: any,
    closed?: any,
    _rowCount?: number,
    /**
     * User Property
     */
    name: string,
    text?: string,
    type?: string,
    children?: string,
    dataType?: string,
    width?: string | number,
    editable?: boolean,
    visible?: boolean,
    align?: string,
    scale?: string,
    roundType?: string,
    fixedScale?: string,
    scaleMax?: string,
    scaleMin?: string,
    showZero?: boolean,
    commaUnit?: string,
    thousandChar?: string,
    decimalChar?: string,
    currencyChar?: string,
    className?:  string,
    resizable?: boolean,
    sortable?: boolean,
    movable?: boolean,
    autoResizable?: boolean,
    autoWidth?: boolean,
    summaryType?: string,
    required?: boolean,
    combo?: any
    format?: boolean,
    kind?: WaColumnKind,
    rowSpan?: any,
    colSpan?: any,
    rowIndex?: any,
    colIndex?: any,
    subRowSpan?: any,
    subColSpan?: any,
    order?: any,
    value?: any,
    header?: any
}