import { WaBase } from '../wa.base';
import { WaDatabase } from '../database/wa.database';
import { WaDataTable } from '../database/wa.data.table';
import { WaDataArrayTable } from '../database/wa.data.array.table';
export declare class WaGridBase extends WaBase {
    gridId: string;
    gridConfig: object;
    grid_mode: string;
    mousePointRange: number;
    isMobile: boolean;
    userAgent: string;
    columns: any;
    headerColumnTable: any[];
    renderer: any;
    infoRenderer: any;
    db: WaDatabase;
    header_column_table: WaDataArrayTable;
    column_table: WaDataTable;
    top_column_table: WaDataTable;
    footer_column_table: WaDataTable;
    sort_column_table: WaDataTable;
    filter_column_table: WaDataTable;
    group_column_table: WaDataTable;
    source_table: WaDataTable;
    view_table: WaDataTable;
    group_table: WaDataTable;
    group_header_table: WaDataTable;
    tree_table: WaDataTable;
    page_table: WaDataTable;
    top_table: WaDataTable;
    footer_table: WaDataTable;
    temp_table: WaDataTable;
    data_update: any[];
    data_insert: any[];
    data_delete: any[];
    info_column_table: WaDataTable;
    panel21_table: WaDataTable;
    panel20_table: WaDataTable;
    panel31_table: WaDataTable;
    cell_template_table: WaDataTable;
    data_select_panel30: object[];
    data_select_panel31: object[];
    pageRowCount: number;
    pageIntRowCount: number;
    startRowIndex: number;
    startCellIndex: number;
    lastRowIndex: number;
    lastCellIndex: number;
    _startRowIndex: number;
    _startCellIndex: number;
    _lastRowIndex: number;
    _lastCellIndex: number;
    selectRangeArray: any[];
    startX: number;
    startY: number;
    lastX: number;
    lastY: number;
    const_filterValue: string;
    const_filterType: string;
    const_filterReset: string;
    const_filterSave: string;
    headerRowCount: number;
    fixedColumnIndex: number;
    headerRowHeight: number;
    rowHeight: number;
    topRowHeight: number;
    footerRowHeight: number;
    code_horizontal: string;
    code_vertical: string;
    constructor(gridId: string, gridConfigs: object);
}
